### ISSUE TITLE
[BUG] Dev 서버 구글 소셜 로그인 실패

### ISSUE THREAD

**Issue by mooncw** [Kernel360/F2-ENGLISH-CHALLENGING-BE#99]
# https 로컬 환경에서 구글 소셜 로그인을 하려하니 400: redirect_uri_mismatch 발생

## Image
![image](https://github.com/user-attachments/assets/e7a33d59-a091-4ecc-9c7e-93f9ef705c9a)

**Comment by mooncw** [comment]
제가 알기론 저번에도 이런 오류가 났었는데, 구글이 등록이 바로 안되서 시간이 지나니깐 된걸로 알고 있는데, 맞을까요?
등록한지 1일 넘은 걸로 기억합니다.

**Comment by tigris24** [comment]
> @tigris24 
> 제가 알기론 저번에도 이런 오류가 났었는데, 구글이 등록이 바로 안되서 시간이 지나니깐 된걸로 알고 있는데, 맞을까요?
> 등록한지 1일 넘은 걸로 기억합니다.

구글 콘솔에 uri 입력을 잘못한게 아니라면 당장은 에러의 이유를 모르겠네요

**Comment by tigris24** [comment]
yml파일 때문에 에러났을 것 같기도 하네요

**Comment by mooncw** [comment]
오잉? 어디부분인지 아시나요?

**Comment by tigris24** [comment]
제가 지금은 확인할 수 없는데 보통 .env는 안바뀌니까 yml에서 로컬만 적용되어 있는다던지 오타가 있다던지 하는 경우가 많았었어서 혹시 싶어사 말씀드렸습니다

**Comment by mooncw** [comment]
음.. 리다이렉션 하는 부분도 없고, 변수로 받는건
    google:
      client-id: ${MY_GOOGLE_CLIENT_ID}
      client-secret: ${MY_GOOGLE_CLIENT_SECRET}
이 부분 밖에 없긴합니다.
오시면 확인 부탁드릴게요 ㅎㅎ..

**Comment by tigris24** [comment]
#198 에서 DEV, PROD 서버 구글 소셜 로그인 해결

**Comment by mooncw** [comment]
yml 파일에 redirect_uri 추가하여 해결
